@startuml
salt
{
{T
+ 结算单升级改造

+++ **结算单接口服务化**
+++++ 商家分库分表及查询接口
+++++ 商家与结算单索引表及查询接口
+++++ 分库分表的聚合查询接口(elastic)

+++ **excel导出**
+++++ 日账单、结算单日前生成
+++++ 区间段内查询，实时导出（elastic）
+++++ shop端异步excel生成并通知

+++ **数据迁移**
+++++ 建表
+++++ 数据迁移


}
}
@enduml