@startuml
salt
{
{T
+ **开普勒 **

+++ **账户入驻**
+++++ 建立passport与账户对应关系表设计与开发。3
+++++ 改造金算盘拦截逻辑和cookie写入逻辑，支持非POP账户的登录。 5
+++++ 单点登录后业务系统传passport与账户关系通知接口。2
+++++ 对公入驻逻辑开发页面调整与逻辑开发、安全考虑。15

+++ **计费**
+++++ 妥投消息收取改造。2
+++++ 预处理环节改造。3
+++++ 计费模型配置，计费逻辑开发。5

+++ **结算 **
+++++ 计费明细同步结算明细。2
+++++ 结算明细处理环节开发。5

+++ **对账 **
+++++ 对账文件生成逻辑开发。5
+++++ 对账列表页面展示底层方法开发。5
+++++ 对账详情页面展示底层方法开发。3

+++ **基于账户的结算单查询改造 **
+++++ shop端结算端基于账户查询改造。10
+++++ man端基于账户相关查询改造。10

+++ **开发联调自测 15天**

}
}
@enduml