@startuml
(*)  --> "是否创建结算账号"
If "创建结算账号" then
--> [Yes] "允许登录金算盘"
--> "登录金算盘"
If "是否创建绑定资金账号" then
--> [Yes] "正常对账"
-->(*)
else
--> "提示补全资金账号信息，并绑定"
endif
-->(*)
else
--> "不允许登录金算盘"
Endif
-->(*)
@enduml