@startuml
salt
{
{T
+ **计费结算系统维护数据 **
+++ **账户入驻**
+++++ 银行卡信息
+++++++ 境内银行卡信息
+++++++++++++ 银行卡号
+++++++++++++ 开户行名称
+++++++++++++ 开户公司名称
+++++++++++++ 开户银行地址
+++++++++++++ 联行号
+++++++++++++ 处理状态
+++++++ 境外银行卡信息
+++++++++++++ 银行卡号
+++++++++++++ 开户行名称
+++++++++++++ 开户公司名称
+++++++++++++ 开户银行地址
+++++++++++++ 开户行国家
+++++++++++++ 开户行国家代码
+++++++++++++ 开户行分行代码(国家是新加坡时需要填写)
+++++++++++++ 开户行RountingNumber
+++++++++++++ 开户行IBANNumber
+++++++++++++ 中转行名称
+++++++++++++ 中转行地址
+++++++++++++ 中转行国家代码
+++++++++++++ 处理状态
+++++++ 网银钱包信息
+++++++++++++ 网银钱包用户名
+++++++++++++ 网银钱包别名
+++++++++++++ 考虑发票接口迁移
+++++++++++++ 处理状态
+++++++ Payoneer
+++++++++++++ payoneer系统中的payeeid
+++++++++++++ payoneer系统中的FIRST_NAME
+++++++++++++ payoneer系统中的LAST_NAME
+++++++++++++ 处理状态

+++ **接口传递**

++++必须传递

+++++ 公司名称
+++++ 法人
+++++ 邮箱(选填)
+++++ 公司地址
+++++ 纳税人识别号（选填/USCI_NO）
+++++ 主体性质(遵循社会组织)
+++++ 商户国家地区代码(CN/US)

+++++ 合同开始时间
+++++ 合同结算时间
+++++ 店铺名称
+++++ 商家类型(金算盘系统分配)
+++++ 商家来源(金算盘系统分配)
+++++ 商家编号
+++++ 公司编号

+++++ 账户类型
+++++ 结算币种
+++++ 合作模式(默认SOP)

+++++ userPin
+++++ 是否主账户
}
}
@enduml