@startuml

fin_fee_detail "1" *-- "many" fin_bill_detail_v17_20160530 : to
fin_fee_detail "1" *-- "many" fin_bill_detail916 : to
fin_fee_detail --> "1" fin_detail_synch20

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes
table(FOO1) {
  primary_key(FIELD1)
  FIELD2
}



table(fin_fee_detail){
+ 费用明细表：1.按商家%32分库 2.按商家%32分表
+ VENDER_ID 结算商家ID
+ ACCOUNT_ID 账户ID
+ STATEMENT_ID 结算单ID
+ STATEMENT_BEGIN_TIME 结算账期开始时间
+ ORDER_ID 业务ID（订单ID,or服务ID）
+ SYNC_STATUS 同步状态0. 未同步1. 同步成功2. 同步失败,
+ ERP_DETAIL_ID ERP明细ID,
+ ORGAN_ID int(11) 机构Id
}

table(fin_bill_detail_v17_20160530){
+ 费用明细大表：1. 按商家%32分库 2.按天分表
+ VENDER_ID 结算商家ID
+ ACCOUNT_ID 账户ID
+ STATEMENT_ID 结算单ID
+ STATEMENT_BEGIN_TIME 结算账期开始时间
+ ORDER_ID 业务ID（订单ID,or服务ID）
+ SYNC_STATUS 同步状态0. 未同步1. 同步成功2. 同步失败,
+ ERP_DETAIL_ID ERP明细ID,
+ ORGAN_ID int(11) 机构Id
}

table(fin_bill_detail916){
+ 费用明细小表：1.按商家%32分库 2.按商家%1024分表
+ VENDER_ID 结算商家ID
+ ACCOUNT_ID 账户ID
+ STATEMENT_ID 结算单ID
+ STATEMENT_BEGIN_TIME 结算账期开始时间
+ ORDER_ID 业务ID（订单ID,or服务ID）
+ SYNC_STATUS 同步状态0. 未同步1. 同步成功2. 同步失败,
+ ERP_DETAIL_ID ERP明细ID,
+ ORGAN_ID int(11) 机构Id
}

table(fin_detail_synch20){
+ BILL_DETAIL_ID  结算单明细表中对应ID
+ SYNCH_STATUS 同步状态：0为未同步，1为已同步
+ CREATED 创建时间
+ MODIFIED 修改时间
+ ORDER_ID 订单ID
+ VENDER_ID 商家ID
+ STATEMENT_ID 结算单ID
}

class DetailSyncStatus {
+ 同步状态枚举类
+ PENDING_SYNC 0：待同步
+ SYNC_FINISH 1：同步完成/待关联
+ PENDING_ASSOCIATE 1：同步完成/待关联
+ ASSOCIATE_FINISH 2：关联完成/待迁移结算明细分区表
+ PENDING_MIGRATE_DETAIL 2：关联完成/待迁移结算明细分区表
+ MIGRATE_DETAIL_FINISH 5：迁移结算明细分区表完成/待结算费用统计处理
+ PENDING_SETTLE_STATS 5：迁移结算明细分区表完成/待结算费用统计处理
+ SETTLE_STATS_FINISH 3：费用费用统计完成/待结算行转列处理
+ PENDING_FEE_CONVERT 3：费用费用统计完成/待结算行转列处理
+ FEE_CONVERT_FINISH 4：结算行转列完成
+ SETTLE_FINISH 4：结算完成
}

@enduml