@startuml
salt
{
{T
+ **O2O分佣 开发工时105天 **

+++ **杨怀**
+++++ POP账户系统对接网银钱包账户验证接口验证是否存在、合法性校验等 |3天 |杨怀
+++++ 门店帮导购员入驻后调用POP账户系统接口、为导购员生成结算账户 |5天 |杨怀
+++++ POP账户系统提供给门店帮电子签接口，门店帮推送电子签信息 |3天 |杨怀
+++++ POP账户系统电子签信息work开发，同步电子签信息到网银钱包 |2天 |杨怀
+++++ POP账户系统对接网银接口电子签信息接口，传送电子签信息（http接口） |3天 |杨怀
+++++ POP账户系统通过手机号获取网银钱包账户别名接口对接(之前是邮箱注册) |3天 |杨怀
+++++ POP账户系统提供给POP收付费系统统一账户收款别名查询服务 |2天 |杨怀
+++++ POP收付费系统对接POP账户系统查询导购员账户别名服务 |2天 |杨怀

+++ **常号**
+++++ POP计费系统对接POP账户系统调取计费关系数据 |2天 |常号
+++++ POP扣点系通为POP计费系统提供扣点比例查询接口 |3天 |常号
+++++ POP计费系统对接扣点系统调取扣点系统比例 |5天 |常号
+++++ POP计费系统接收订单消息后针对订单进行逻辑拆分 1.走原始原始分账委托逻辑 2.分佣逻辑 |5天 |常号
+++++ POP计费系统针对导购员分佣20天后合并分佣逻辑开发 |20天 |常号

+++ **张学刚**
+++++ POP计费系统生成费用明细数据改造（主要区分对公对私） |2天 |张学刚
+++++ POP计费系统费用明细与账单关联改造（主要区分对公对私） |3天 |张学刚
+++++ POP结算系统同步分账费用明细给POP收付费系统接口改造（主要区分对公对私）|3天 |张学刚
+++++ POP收付费系统接收POP结算系统分账费用明细消息接口改造 |2天 |张学刚
+++++ POP收付款逻辑表结构调整区分对公收付款与对私收付款（暂定、可能通过账户查询） |6天 |张学刚
+++++ POP收付款系统对接网银支付接口、根据不同分账场景走不同策略接口 |10天 |张学刚
+++ **暂时取消**
+++++ POP账户系统对接门店帮根据导购员查询导购员与分销商、品牌商关系 |3天 |杨怀（本接口暂时取消，现在不强制先款后款，所以暂时不用）
+++++ POP账户系统封装导购员与分销商、品牌商关联关系为计费系统提供服务接口 |3天 |杨怀(同上)

+++ **开发联调自测 15天**

}
}
@enduml