@startuml

title 预付费收付费流程图

(*) --> "付款操作"
'根据付款类型判断以及余额判断是否需要拆收付款单'
    --> "拆单"
if "是否预付款单" then
    ->[true] "调用支付接口回写预付付款单状态"
    --> "记录收付流水"
    --> "操作余额"
    --> "流程最后结点"
 else
  -->[false] "调用支付接口回写收付款单状态"
endif

--> "流程最后结点"
-->(*)

@enduml